/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InstitucionalRouteImport } from './routes/institucional'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstitucionalIndexRouteImport } from './routes/institucional.index'
import { Route as InstitucionalSobreRouteImport } from './routes/institucional.sobre'
import { Route as InstitucionalEspecialidadesRouteImport } from './routes/institucional.especialidades'

const InstitucionalRoute = InstitucionalRouteImport.update({
  id: '/institucional',
  path: '/institucional',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitucionalIndexRoute = InstitucionalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstitucionalRoute,
} as any)
const InstitucionalSobreRoute = InstitucionalSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => InstitucionalRoute,
} as any)
const InstitucionalEspecialidadesRoute =
  InstitucionalEspecialidadesRouteImport.update({
    id: '/especialidades',
    path: '/especialidades',
    getParentRoute: () => InstitucionalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/institucional': typeof InstitucionalRouteWithChildren
  '/institucional/especialidades': typeof InstitucionalEspecialidadesRoute
  '/institucional/sobre': typeof InstitucionalSobreRoute
  '/institucional/': typeof InstitucionalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/institucional/especialidades': typeof InstitucionalEspecialidadesRoute
  '/institucional/sobre': typeof InstitucionalSobreRoute
  '/institucional': typeof InstitucionalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/institucional': typeof InstitucionalRouteWithChildren
  '/institucional/especialidades': typeof InstitucionalEspecialidadesRoute
  '/institucional/sobre': typeof InstitucionalSobreRoute
  '/institucional/': typeof InstitucionalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/institucional'
    | '/institucional/especialidades'
    | '/institucional/sobre'
    | '/institucional/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/institucional/especialidades'
    | '/institucional/sobre'
    | '/institucional'
  id:
    | '__root__'
    | '/'
    | '/institucional'
    | '/institucional/especialidades'
    | '/institucional/sobre'
    | '/institucional/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstitucionalRoute: typeof InstitucionalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/institucional': {
      id: '/institucional'
      path: '/institucional'
      fullPath: '/institucional'
      preLoaderRoute: typeof InstitucionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institucional/': {
      id: '/institucional/'
      path: '/'
      fullPath: '/institucional/'
      preLoaderRoute: typeof InstitucionalIndexRouteImport
      parentRoute: typeof InstitucionalRoute
    }
    '/institucional/sobre': {
      id: '/institucional/sobre'
      path: '/sobre'
      fullPath: '/institucional/sobre'
      preLoaderRoute: typeof InstitucionalSobreRouteImport
      parentRoute: typeof InstitucionalRoute
    }
    '/institucional/especialidades': {
      id: '/institucional/especialidades'
      path: '/especialidades'
      fullPath: '/institucional/especialidades'
      preLoaderRoute: typeof InstitucionalEspecialidadesRouteImport
      parentRoute: typeof InstitucionalRoute
    }
  }
}

interface InstitucionalRouteChildren {
  InstitucionalEspecialidadesRoute: typeof InstitucionalEspecialidadesRoute
  InstitucionalSobreRoute: typeof InstitucionalSobreRoute
  InstitucionalIndexRoute: typeof InstitucionalIndexRoute
}

const InstitucionalRouteChildren: InstitucionalRouteChildren = {
  InstitucionalEspecialidadesRoute: InstitucionalEspecialidadesRoute,
  InstitucionalSobreRoute: InstitucionalSobreRoute,
  InstitucionalIndexRoute: InstitucionalIndexRoute,
}

const InstitucionalRouteWithChildren = InstitucionalRoute._addFileChildren(
  InstitucionalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstitucionalRoute: InstitucionalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
